export default {
    'defaultKey':'default',//默认主题
    'themes':[{
        key:'default',
        name:'默认',
        primary:'#409eff',//主色调，ep默认亮蓝
        bgColor:'#17233D',//蓝黑
        textColor:'#ffffff',//白灰AEB2BB
        activeTextColor:'#409EFF',//白色
        sideBorderColor:'#a3a5ac',//菜单边框色
        bodyBgColor:'#f0f0f0',//body背景色
    },
    {
        key:'black',
        name:'夜晚',
        primary:'#3288df',//主色调，亮蓝深
        bgColor:'#303133',//黑色背景
        textColor:'#ffffff',//白色字
        activeTextColor:'#2180df',//亮蓝
        sideBorderColor:'#a3a5ac',//菜单边框色
        bodyBgColor:'#d4d4d4',//body背景色
    },
    {
        key:'white',
        name:'简约',
        primary:'#409eff',//主色调，ep默认亮蓝
        bgColor:'#ffffff',//#ffffff,#545c64
        textColor:'#303133',//黑色字
        activeTextColor:'#409EFF',//#409EFF,#ffd04b
        sideBorderColor:'#c8c9cc',//菜单边框色
        bodyBgColor:'#fdfbfb',//body背景色
    }]
}